import Head from 'next/head'
import { Banner } from '../components'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="font-main w-[92%] lg:w-[86%] xl:w-[75%] text-white pt-6 mx-auto min-h-screen flex flex-col justify-between">
      <Head>
        <title>COFFEY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner/>
      </main>

      <footer className="text-center py-3 border-t border-neutral-600">
        <p>Created by Anes Diaf</p>
      </footer>
    </div>
  )
}
